### ISSUE TITLE
Error···help！

### ISSUE THREAD

**Issue by wudideasdf** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#1]
D:\ComfyUI-ainewsto\ComfyUI\python_miniconda\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "D:\ComfyUI-ainewsto\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-ainewsto\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\__init__.py", line 46, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI-ainewsto\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 22, in <module>
    from .LivePortrait.src.live_portrait_wrapper import LivePortraitWrapper
  File "D:\ComfyUI-ainewsto\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\LivePortrait\src\live_portrait_wrapper.py", line 10, in <module>
    from config.inference_config import InferenceConfig
ModuleNotFoundError: No module named 'config.inference_config'

Cannot import D:\ComfyUI-ainewsto\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait module for custom nodes: No module named 'config.inference_config'

**Comment by PowerHouseMan** [comment]
I'm not sure why, but I fixed what I expected. Try again!

**Comment by wudideasdf** [comment]
> I'm not sure why, but I fixed what I expected.我不知道为什么，但我修复了我的预期。 Please try again and let me know if it works. :)请再试一次，让我知道它是否有效。 :)

Thanks a lot, The update seems to be working, I can now use your plugin correctly,
