### ISSUE TITLE
Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by physeo** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#42]
Updated ComfyUI and all extensions. Using the Basic workflow. Getting error below:

`
# ComfyUI Error Report
## Error Details
- **Node Type:** ExpressionEditor
- **Exception Type:** safetensors_rust.SafetensorError
- **Exception Message:** Error while deserializing header: MetadataIncompleteBuffer
## Stack Trace
```
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 895, in run
    self.psi = g_engine.prepare_source(src_image, crop_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 362, in prepare_source
    engine = self.get_pipeline()
             ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 322, in get_pipeline
    self.load_models()

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 203, in load_models
    warping_module = self.load_model(model_config, 'warping_module')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 189, in load_model
    model.load_state_dict(comfy.utils.load_torch_file(ckpt_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\physe\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-1-gc27ebeb
- **Arguments:** ComfyUI\main.py --windows-standalone-build --preview-method auto
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.2.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25769148416
  - **VRAM Free:** 24425529344
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-09-06 13:44:00,226 - root - INFO - Total VRAM 24575 MB, total RAM 32696 MB
2024-09-06 13:44:00,226 - root - INFO - pytorch version: 2.2.1+cu121
2024-09-06 13:44:00,227 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-06 13:44:00,227 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-09-06 13:44:01,707 - root - INFO - Using pytorch cross attention
2024-09-06 13:44:02,317 - root - INFO - [Prompt Server] web root: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\web
2024-09-06 13:44:02,320 - root - INFO - Adding extra search path checkpoints C:\Users\physe\AI\models/Stable-diffusion
2024-09-06 13:44:02,320 - root - INFO - Adding extra search path configs C:\Users\physe\AI\models/Stable-diffusion
2024-09-06 13:44:02,320 - root - INFO - Adding extra search path vae C:\Users\physe\AI\models/VAE
2024-09-06 13:44:02,321 - root - INFO - Adding extra search path loras C:\Users\physe\AI\models/Lora
2024-09-06 13:44:02,321 - root - INFO - Adding extra search path loras C:\Users\physe\AI\models/LyCORIS
2024-09-06 13:44:02,321 - root - INFO - Adding extra search path upscale_models C:\Users\physe\AI\models/ESRGAN
2024-09-06 13:44:02,321 - root - INFO - Adding extra search path upscale_models C:\Users\physe\AI\models/RealESRGAN
2024-09-06 13:44:02,321 - root - INFO - Adding extra search path upscale_models C:\Users\physe\AI\models/SwinIR
2024-09-06 13:44:02,321 - root - INFO - Adding extra search path embeddings C:\Users\physe\AI\embeddings
2024-09-06 13:44:02,321 - root - INFO - Adding extra search path hypernetworks C:\Users\physe\AI\models/hypernetworks
2024-09-06 13:44:02,321 - root - INFO - Adding extra search path controlnet C:\Users\physe\AI\models/ControlNet
2024-09-06 13:44:02,322 - root - INFO - Adding extra search path clip_vision C:\Users\physe\AI\models/clip_vision
2024-09-06 13:44:02,322 - root - INFO - Adding extra search path inpaint C:\Users\physe\AI\models/inpaint
2024-09-06 13:44:05,570 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

2024-09-06 13:44:05,570 - root - WARNING - Cannot import C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'
2024-09-06 13:44:08,912 - root - INFO - 
Import times for custom nodes:
2024-09-06 13:44:08,912 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\canvas_tab
2024-09-06 13:44:08,912 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\kohya_hiresfix.py
2024-09-06 13:44:08,913 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-06 13:44:08,913 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\attention-couple-ComfyUI
2024-09-06 13:44:08,913 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\TTP_tile_preprocessor_v5.py
2024-09-06 13:44:08,913 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-06 13:44:08,914 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch
2024-09-06 13:44:08,914 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ComfyCouple
2024-09-06 13:44:08,914 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
2024-09-06 13:44:08,914 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_aspect_ratios
2024-09-06 13:44:08,914 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-06 13:44:08,915 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-09-06 13:44:08,915 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
2024-09-06 13:44:08,915 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-06 13:44:08,915 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
2024-09-06 13:44:08,915 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-09-06 13:44:08,915 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-09-06 13:44:08,916 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-06 13:44:08,916 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-06 13:44:08,916 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-06 13:44:08,916 - root - INFO -    0.0 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-06 13:44:08,916 - root - INFO -    0.1 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-LDSR
2024-09-06 13:44:08,916 - root - INFO -    0.1 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-09-06 13:44:08,917 - root - INFO -    0.1 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-09-06 13:44:08,917 - root - INFO -    0.3 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
2024-09-06 13:44:08,917 - root - INFO -    0.4 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-06 13:44:08,917 - root - INFO -    0.5 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
2024-09-06 13:44:08,917 - root - INFO -    0.8 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-09-06 13:44:08,917 - root - INFO -    0.8 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\a-person-mask-generator
2024-09-06 13:44:08,917 - root - INFO -    2.3 seconds: C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-09-06 13:44:08,917 - root - INFO - 
2024-09-06 13:44:08,929 - root - INFO - Starting server

2024-09-06 13:44:08,929 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-06 13:44:19,874 - root - INFO - got prompt
2024-09-06 13:44:20,806 - root - ERROR - !!! Exception during processing !!! Error while deserializing header: MetadataIncompleteBuffer
2024-09-06 13:44:20,815 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 895, in run
    self.psi = g_engine.prepare_source(src_image, crop_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 362, in prepare_source
    engine = self.get_pipeline()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 322, in get_pipeline
    self.load_models()
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 203, in load_models
    warping_module = self.load_model(model_config, 'warping_module')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 189, in load_model
    model.load_state_dict(comfy.utils.load_torch_file(ckpt_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

2024-09-06 13:44:20,817 - root - INFO - Prompt executed in 0.94 seconds
2024-09-06 13:45:18,312 - root - INFO - got prompt
2024-09-06 13:45:18,857 - root - ERROR - !!! Exception during processing !!! Error while deserializing header: MetadataIncompleteBuffer
2024-09-06 13:45:18,857 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 895, in run
    self.psi = g_engine.prepare_source(src_image, crop_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 362, in prepare_source
    engine = self.get_pipeline()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 322, in get_pipeline
    self.load_models()
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 203, in load_models
    warping_module = self.load_model(model_config, 'warping_module')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 189, in load_model
    model.load_state_dict(comfy.utils.load_torch_file(ckpt_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

2024-09-06 13:45:18,859 - root - INFO - Prompt executed in 0.54 seconds
2024-09-06 13:45:25,688 - root - INFO - got prompt
2024-09-06 13:45:26,249 - root - ERROR - !!! Exception during processing !!! Error while deserializing header: MetadataIncompleteBuffer
2024-09-06 13:45:26,250 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 895, in run
    self.psi = g_engine.prepare_source(src_image, crop_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 362, in prepare_source
    engine = self.get_pipeline()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 322, in get_pipeline
    self.load_models()
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 203, in load_models
    warping_module = self.load_model(model_config, 'warping_module')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 189, in load_model
    model.load_state_dict(comfy.utils.load_torch_file(ckpt_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

2024-09-06 13:45:26,252 - root - INFO - Prompt executed in 0.56 seconds
2024-09-06 16:07:55,045 - root - INFO - got prompt
2024-09-06 16:07:56,289 - root - ERROR - !!! Exception during processing !!! Error while deserializing header: MetadataIncompleteBuffer
2024-09-06 16:07:56,304 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 895, in run
    self.psi = g_engine.prepare_source(src_image, crop_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 362, in prepare_source
    engine = self.get_pipeline()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 322, in get_pipeline
    self.load_models()
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 203, in load_models
    warping_module = self.load_model(model_config, 'warping_module')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 189, in load_model
    model.load_state_dict(comfy.utils.load_torch_file(ckpt_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\physe\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

2024-09-06 16:07:56,306 - root - INFO - Prompt executed in 1.20 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":33,"last_link_id":40,"nodes":[{"id":33,"type":"SaveImage","pos":{"0":1351,"1":373.7899169921875},"size":{"0":257.8363037109375,"1":270},"flags":{},"order":2,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":40}],"outputs":[],"properties":{},"widgets_values":["ExpressionEditing"]},{"id":14,"type":"ExpressionEditor","pos":{"0":1044,"1":362.7899169921875},"size":{"0":260.81048583984375,"1":690},"flags":{},"order":1,"mode":0,"inputs":[{"name":"src_image","type":"IMAGE","link":19},{"name":"motion_link","type":"EDITOR_LINK","link":null},{"name":"sample_image","type":"IMAGE","link":null},{"name":"add_exp","type":"EXP_DATA","link":null}],"outputs":[{"name":"image","type":"IMAGE","links":[40],"slot_index":0,"shape":3},{"name":"motion_link","type":"EDITOR_LINK","links":null,"shape":3},{"name":"save_exp","type":"EXP_DATA","links":null,"shape":3}],"properties":{"Node name for S&R":"ExpressionEditor"},"widgets_values":[5.5,0,0,0,0,23.5,0,0,0,0,0,0,1,1,"OnlyExpression",1.7000000000000002]},{"id":15,"type":"LoadImage","pos":{"0":776,"1":366.7899169921875},"size":{"0":210,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[19],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["PXL_20240602_151637768.jpg","image"]}],"links":[[19,15,0,14,0,"IMAGE"],[40,14,0,33,0,"IMAGE"]],"groups":[{"title":"Simple facial expression editing","bounding":[745,261,896,835],"color":"#88A","font_size":30,"flags":{}}],"config":{},"extra":{"ds":{"scale":1.2100000000000009,"offset":[-136.17277228401807,-177.73867298976512]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
`

**Comment by zz1625** [comment]
Did you solve it? I also made this mistake.

**Comment by tangbob** [comment]
same problem here

**Comment by tangbob** [comment]
The issue related to the model files in the model directory of liveportait has been resolved by deleting and re-downloading the five model files.

**Comment by tangbob** [comment]
close it

**Comment by Anarchick** [comment]
I had the same issue and solve this following this steps (I use Stability Matrix) : 
        - Download all files from https://huggingface.co/Kijai/LivePortrait_safetensors/tree/main and put them in StabilityMatrix\Data\Packages\ComfyUI\models\liveportrait
	- Download all files from https://drive.google.com/drive/folders/1TQiugdYlNPIZ7gPuqeIxK9cUReMCGKw5 and put them in StabilityMatrix\Data\Packages\ComfyUI\models\insightface
	- Open cmd terminal in StabilityMatrix\Data\Assets\Python310, and execute : "python.exe -m pip install insightface"
	
I don't know if it's only step 1 / 2 / 3 or both that fix it
