### ISSUE TITLE
Advanced LivePortrait make comfy crash

### ISSUE THREAD

**Issue by McLaniel** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#55]
Hello! I use comfyUI thru vision of chaos, and every time I tried to install Advanced LivePortrait node it make my comfyUI crash. It only happen with this node. Is there a bug on the node right now?

**Comment by McLaniel** [comment]
===========================================================================
ComfyUI
https://github.com/comfyanonymous/ComfyUI
Executing command line;
"E:\MachineLearning\Text To Image\ComfyUI\Run_ComfyUI.bat"
===========================================================================

*** VoC - activating virtual environment
*** VoC - starting
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-23 16:32:06.425303
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: E:\MachineLearning\Text To Image\ComfyUI\ComfyUI
** Log path: E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'numpy>=1.26.4']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting numpy>=1.26.4
   Using cached numpy-2.1.1-cp310-cp310-win_amd64.whl.metadata (59 kB)
 Using cached numpy-2.1.1-cp310-cp310-win_amd64.whl (12.9 MB)
 Installing collected packages: numpy
   Attempting uninstall: numpy
     Found existing installation: numpy 1.26.3
     Uninstalling numpy-1.26.3:
       Successfully uninstalled numpy-1.26.3
 Successfully installed numpy-2.1.1

## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'opencv-python-headless']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting opencv-python-headless
   Using cached opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
  Using cached opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
 Installing collected packages: opencv-python-headless
 Successfully installed opencv-python-headless-4.10.0.84

## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'imageio-ffmpeg>=0.5.1']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting imageio-ffmpeg>=0.5.1
   Using cached imageio_ffmpeg-0.5.1-py3-none-win_amd64.whl.metadata (1.6 kB)
  Using cached imageio_ffmpeg-0.5.1-py3-none-win_amd64.whl (22.6 MB)
 Installing collected packages: imageio-ffmpeg
 Successfully installed imageio-ffmpeg-0.5.1

## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'lmdb>=1.4.1']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting lmdb>=1.4.1
   Using cached lmdb-1.5.1-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
 Using cached lmdb-1.5.1-cp310-cp310-win_amd64.whl (100 kB)
 Installing collected packages: lmdb
 Successfully installed lmdb-1.5.1

## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'timm>=1.0.7']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting timm>=1.0.7
   Using cached timm-1.0.9-py3-none-any.whl.metadata (42 kB)
                        Using cached timm-1.0.9-py3-none-any.whl (2.3 MB)
 Installing collected packages: timm
 Successfully installed timm-1.0.9
[SKIP] Downgrading pip package isn't allowed: rich (cur=13.8.1)

## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'albumentations>=1.4.10']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting albumentations>=1.4.10
   Using cached albumentations-1.4.16-py3-none-any.whl.metadata (38 kB)
     Collecting pydantic>=2.7.0 (from albumentations>=1.4.10)
   Using cached pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
 Collecting albucore==0.0.17 (from albumentations>=1.4.10)
   Using cached albucore-0.0.17-py3-none-any.whl.metadata (3.1 kB)
 Collecting eval-type-backport (from albumentations>=1.4.10)
   Using cached eval_type_backport-0.2.0-py3-none-any.whl.metadata (2.2 kB)
  Collecting annotated-types>=0.6.0 (from pydantic>=2.7.0->albumentations>=1.4.10)
   Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
 Collecting pydantic-core==2.23.4 (from pydantic>=2.7.0->albumentations>=1.4.10)
   Using cached pydantic_core-2.23.4-cp310-none-win_amd64.whl.metadata (6.7 kB)
        Using cached albumentations-1.4.16-py3-none-any.whl (214 kB)
 Using cached albucore-0.0.17-py3-none-any.whl (10 kB)
 Using cached pydantic-2.9.2-py3-none-any.whl (434 kB)
 Using cached pydantic_core-2.23.4-cp310-none-win_amd64.whl (1.9 MB)
 Using cached eval_type_backport-0.2.0-py3-none-any.whl (5.9 kB)
 Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
 Installing collected packages: pydantic-core, eval-type-backport, annotated-types, pydantic, albucore, albumentations
 Successfully installed albucore-0.0.17 albumentations-1.4.16 annotated-types-0.7.0 eval-type-backport-0.2.0 pydantic-2.9.2 pydantic-core-2.23.4

## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'ultralytics']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting ultralytics
   Using cached ultralytics-8.2.99-py3-none-any.whl.metadata (39 kB)
 Collecting numpy<2.0.0,>=1.23.0 (from ultralytics)
   Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
           Collecting py-cpuinfo (from ultralytics)
   Using cached py_cpuinfo-9.0.0-py3-none-any.whl.metadata (794 bytes)
 Collecting pandas>=1.1.4 (from ultralytics)
   Using cached pandas-2.2.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
 Collecting seaborn>=0.11.0 (from ultralytics)
   Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
 Collecting ultralytics-thop>=2.0.0 (from ultralytics)
   Using cached ultralytics_thop-2.0.8-py3-none-any.whl.metadata (9.3 kB)
 Collecting torch>=1.8.0 (from ultralytics)
   Using cached torch-2.4.1-cp310-cp310-win_amd64.whl.metadata (27 kB)
        Collecting pytz>=2020.1 (from pandas>=1.1.4->ultralytics)
   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
 Collecting tzdata>=2022.7 (from pandas>=1.1.4->ultralytics)
   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
           INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
 Collecting torchvision>=0.9.0 (from ultralytics)
   Using cached torchvision-0.19.1-cp310-cp310-win_amd64.whl.metadata (6.1 kB)
     Using cached ultralytics-8.2.99-py3-none-any.whl (874 kB)
 Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
 Using cached pandas-2.2.3-cp310-cp310-win_amd64.whl (11.6 MB)
 Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
 Using cached torch-2.4.1-cp310-cp310-win_amd64.whl (199.4 MB)
 Using cached torchvision-0.19.1-cp310-cp310-win_amd64.whl (1.3 MB)
 Using cached ultralytics_thop-2.0.8-py3-none-any.whl (26 kB)
 Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
 Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
 Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
 Installing collected packages: pytz, py-cpuinfo, tzdata, numpy, torch, pandas, ultralytics-thop, torchvision, seaborn, ultralytics
   Attempting uninstall: numpy
     Found existing installation: numpy 2.1.1
     Uninstalling numpy-2.1.1:
       Successfully uninstalled numpy-2.1.1
   Attempting uninstall: torch
     Found existing installation: torch 2.4.0+cu118
     Uninstalling torch-2.4.0+cu118:
       Successfully uninstalled torch-2.4.0+cu118
   Attempting uninstall: torchvision
     Found existing installation: torchvision 0.19.0+cu118
     Uninstalling torchvision-0.19.0+cu118:
       Successfully uninstalled torchvision-0.19.0+cu118
[!] ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[!] torchaudio 2.4.0+cu118 requires torch==2.4.0+cu118, but you have torch 2.4.1 which is incompatible.
[!] xformers 0.0.27.post2+cu118 requires torch==2.4.0, but you have torch 2.4.1 which is incompatible.
 Successfully installed numpy-1.26.4 pandas-2.2.3 py-cpuinfo-9.0.0 pytz-2024.2 seaborn-0.13.2 torch-2.4.1 torchvision-0.19.1 tzdata-2024.2 ultralytics-8.2.99 ultralytics-thop-2.0.8

## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'tyro==0.8.5']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting tyro==0.8.5
   Using cached tyro-0.8.5-py3-none-any.whl.metadata (8.2 kB)
 Collecting docstring-parser>=0.16 (from tyro==0.8.5)
   Using cached docstring_parser-0.16-py3-none-any.whl.metadata (3.0 kB)
   Collecting shtab>=1.5.6 (from tyro==0.8.5)
   Using cached shtab-1.7.1-py3-none-any.whl.metadata (7.3 kB)
     Using cached tyro-0.8.5-py3-none-any.whl (103 kB)
 Using cached docstring_parser-0.16-py3-none-any.whl (36 kB)
 Using cached shtab-1.7.1-py3-none-any.whl (14 kB)
 Installing collected packages: shtab, docstring-parser, tyro
 Successfully installed docstring-parser-0.16 shtab-1.7.1 tyro-0.8.5

## ComfyUI-Manager: EXECUTE => ['E:\\MachineLearning\\Text To Image\\ComfyUI\\ComfyUI\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'dill']

## Execute install/(de)activation script for 'E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait'
 Collecting dill
   Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
 Using cached dill-0.3.8-py3-none-any.whl (116 kB)
 Installing collected packages: dill
 Successfully installed dill-0.3.8

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.0 seconds: E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
  60.1 seconds: E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\main.py", line 90, in <module>
    import execution
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\comfy\model_management.py", line 143, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\comfy\model_management.py", line 112, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\.venv\lib\site-packages\torch\cuda\__init__.py", line 878, in current_device
    _lazy_init()
  File "E:\MachineLearning\Text To Image\ComfyUI\ComfyUI\.venv\lib\site-packages\torch\cuda\__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
*** VoC - done

===========================================================================
Finished in 01m02s
===========================================================================
