### ISSUE TITLE
ExpressionEditor and AdvancedLivePortrait nodes are missing and I can't fix it

### ISSUE THREAD

**Issue by FireJach** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#59]
I did the obvious things such as updating, using the manager to download the missing ones, refreshing etc.

Im totally new. I have never coded. Please, explain any solution with details. Thank you

Here is the log:

[Prompt Server] web root: F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\web
F:\Jaś\ucomfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 11, in <module>
    import dill
ModuleNotFoundError: No module named 'dill'

Cannot import F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait module for custom nodes: No module named 'dill'
### ComfyUI Revision: 2746 [614377ab] | Released on '2024-10-07'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

Import times for custom nodes:
   0.0 seconds: F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.6 seconds: F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.9 seconds: F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.6 seconds (IMPORT FAILED): F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   2.2 seconds: F:\Jaś\ucomfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite

Starting server

**Comment by grokiki** [comment]
same problem ...
